version: "3.7"

volumes:
  logs:
    driver: local

services:
  ginger2:
    build: docker/ginger2
    depends_on:
      - db
      - picasso-ws
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
  picasso-ws:
    build: docker/picasso-ws
    volumes:
      - ./docker/picasso-ws/files:/var/www/
  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ginger
      MARIADB_USER: ginger
      MARIADB_PASSWORD: ginger
    ports:
      - "8082:3306"
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
