name: Build & test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start the database
        run: docker-compose up -d db
      - name: Build the images
        run: docker-compose build
      - name: Start the stack
        run: docker-compose up -d
  configure:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Create test env
        run: cp config/env.example.php config/env.php
      - name: Composer install
        run: docker-compose run --rm ginger2 composer install
      - name: execute database migrations
        run: docker-compose run --rm ginger2 vendor/bin/phoenix migrate
  test:
    needs: [build, configure]
    runs-on: ubuntu-latest
    steps:
      - name: Run test suite
        run: docker-compose exec -T --privileged ginger2 composer test:coverage:clover
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          docker-compose exec -T ginger2 composer require --dev php-coveralls/php-coveralls
          docker-compose exec -T -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN ginger2 vendor/bin/php-coveralls -v
