name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d && sleep 10s
      - name: Create test env
        run: cp config/env.example.php config/env.php
      - name: Composer install
        run: docker-compose run ginger2 composer install
      - name: Run test suite
        run: docker-compose exec -T --privileged ginger2 composer test:coverage:clover
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker-compose exec -T ginger2 composer require --dev php-coveralls/php-coveralls
          docker-compose exec -T -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN ginger2 vendor/bin/php-coveralls -v
